name: Deploy
run-name: ${{ github.actor }} Deploy 🚀

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          fvm install
          fvm flutter pub get 
          fvm flutter --version

      - name: Build web
        run: fvm flutter build web --release --base-href="/trend_vocab/"

      - name: Deploy web
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
